# Generated by Django 2.2.1 on 2019-05-04 13:23

from django.db import migrations, models
import utilities.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('new_phone', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('new_email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('password', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('to_reset', models.BooleanField(db_index=True, default=False)),
                ('to_change_phone', models.BooleanField(db_index=True, default=False)),
                ('to_change_email', models.BooleanField(db_index=True, default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utilities.upload.avatar_upload_v2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TokenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
