# Generated by Django 2.2.1 on 2019-05-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='activation',
            index_together={('phone', 'email', 'used')},
        ),
        migrations.AlterIndexTogether(
            name='tokenlog',
            index_together={('token', 'user')},
        ),
    ]
