# Generated by Django 2.2.1 on 2019-05-11 06:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_word_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
