# Generated by Django 2.2.1 on 2019-05-04 13:23

from django.db import migrations, models
import utilities.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('language', models.IntegerField(choices=[(1, 'русский'), (2, 'қазақша'), (3, 'english')], default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utilities.upload.avatar_upload)),
                ('avatar_big', models.ImageField(blank=True, null=True, upload_to=utilities.upload.avatar_upload)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
